{% set version = "2.18.1" %}

package:
  name: pre-commit
  version: {{ version }}

source:
  url: https://github.com/pre-commit/pre-commit/archive/v{{ version }}.tar.gz
  sha256: 789cdf1878fb475b0d84620cd9f90400f68e102588db60abc04916268266f372

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - pre-commit = pre_commit.main:main
    - pre-commit-validate-config = pre_commit.clientlib:validate_config_main
    - pre-commit-validate-manifest = pre_commit.clientlib:validate_manifest_main

outputs:
  - name: pre-commit
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - cfgv >=2.0.0
        - identify >=1.0.0
        - importlib_metadata  # [py<38]
        - importlib_resources <5.3  # [py<37]
        - nodeenv >=0.11.1
        - python >=3.6.1
        - pyyaml >=5.1
        - toml
        - virtualenv >=20.0.8
    test:
      requires:
        - pip
      imports:
        - pre_commit
        - pre_commit.commands
        - pre_commit.languages
      commands:
        - pip check
        - pre-commit --help
        - pre-commit-validate-config --help
        - pre-commit-validate-manifest --help

  - name: pre_commit
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pre-commit', max_pin="x.x.x") }}
    test:
      imports:
        - pre_commit

about:
  home: http://pre-commit.com/
  license: MIT
  license_file: LICENSE
  summary: A framework for managing and maintaining multi-language pre-commit hooks.
  license_family: MIT
  dev_url: https://github.com/pre-commit/pre-commit
  doc_url: https://github.com/pre-commit/pre-commit

extra:
  recipe-maintainers:
    - deadsnakes-issues-bot
    - nicoddemus
    - xmnlab
