{% set name = "pre-commit" %}
{% set version = "1.21.0" %}
{% set hash_type = "sha256" %}
{% set hash = "9cdc791bfad86b3648a5801518bbfb3ad7cb66f74a4681b10d8dd34d4032cb59" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/pre-commit/pre-commit/archive/v{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pre-commit = pre_commit.main:main
    - pre-commit-validate-config = pre_commit.clientlib:validate_config_main
    - pre-commit-validate-manifest = pre_commit.clientlib:validate_manifest_main

requirements:
  host:
    - pip
    - python

  run:
    - aspy.yaml
    - cached-property
    - cfgv >=2.0.0
    - identify >=1.0.0
    - importlib_metadata  # [py<38]
    - importlib_resources  # [py<37]
    - nodeenv >=0.11.1
    - python
    - pyyaml
    - six
    - toml
    - virtualenv >=15.2
    - futures  # [py2k]

test:
  imports:
    - pre_commit
    - pre_commit.commands
    - pre_commit.languages
  commands:
    - pre-commit --help
    - pre-commit-validate-config --help
    - pre-commit-validate-manifest --help

about:
  home: http://pre-commit.com/
  license: MIT
  license_file: LICENSE
  summary: 'A framework for managing and maintaining multi-language pre-commit hooks.'
  license_family: MIT
  dev_url: https://github.com/pre-commit/pre-commit
  doc_url: https://github.com/pre-commit/pre-commit

extra:
  recipe-maintainers:
    - deadsnakes-issues-bot
    - nicoddemus
    - xmnlab
