{% set version = "3.3.2" %}

package:
  name: pre-commit
  version: {{ version }}

source:
  url: https://github.com/pre-commit/pre-commit/archive/v{{ version }}.tar.gz
  sha256: 92bd09f231f84297b31ef272f1bdd126df30d57a0482345a93ee350ca44c87b8

build:
  number: 0
  noarch: python
  entry_points:
    - pre-commit = pre_commit.main:main
    - pre-commit-validate-config = pre_commit.clientlib:validate_config_main
    - pre-commit-validate-manifest = pre_commit.clientlib:validate_manifest_main

outputs:
  - name: pre-commit
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python >=3.8
      run:
        - cfgv >=2.0.0
        - identify >=1.0.0
        - nodeenv >=0.11.1
        - python >=3.8
        - pyyaml >=5.1
        - virtualenv >=20.10.0
    test:
      requires:
        - pip
      imports:
        - pre_commit
        - pre_commit.commands
        - pre_commit.languages
      commands:
        - pip check
        - pre-commit --help
        - pre-commit-validate-config --help
        - pre-commit-validate-manifest --help

  - name: pre_commit
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pre-commit', max_pin="x.x.x") }}
    test:
      imports:
        - pre_commit

about:
  home: http://pre-commit.com/
  license: MIT
  license_file: LICENSE
  summary: A framework for managing and maintaining multi-language pre-commit hooks.
  license_family: MIT
  dev_url: https://github.com/pre-commit/pre-commit
  doc_url: https://github.com/pre-commit/pre-commit

extra:
  recipe-maintainers:
    - deadsnakes-issues-bot
    - nicoddemus
    - xmnlab
